version: "2.2"
services:
  server:
    build: .
    ports:
      - 8000:8000
    command: nodemon /var/www/events/server/src/index.js --ignore /var/www/events/client
    env_file:
            - server/local.env
    environment:
      - AWS_ACCESS_KEY_ID=AKIAI5EWIGUGQVR6D6SQ
      - AWS_SECRET_ACCESS_KEY=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
    volumes:
      - ./server/src:/var/www/events/server/src
      - ./server/package.json:/var/www/events/server/package.json
      - ./client/build:/var/www/events/client
      - ./client/templates:/var/www/events/templates
  postgres:
    ports:
      # psql -h localhost -p 9000 -U postgres -w -d airconfig
      - 9000:5432
    build:
      context: .
      dockerfile: postgres.dockerfile
  redis:
    image: redis
